name = "Chaos;Child Steam"
description = """# Extracts Chaos;Child Steam version files.\n
Character conversion is supported to plain .PNG files for chara.mpk.
"""
filetype = "mpk"
path = "CHAOS;CHILD/USRDIR/"
sprites = ["chara.mpk"]
processor = "lay"
pfiletype = "lay"
