name = "Steins;Gate Re:Boot Steam"
description = "# Steins;Gate Re:Boot Steam version extractor\nIf convert sprites is ticked, files marked as sprites are extracted twice, once just extracted and a second time decompilled, like the rest of the archives. This is so tools designed to use the compiled versions, like FreeMoteViewer can work."
filetype = "info.psb.m"
path = "SGRE/wind3d11data"
mkey = "detect ../sgre_steam.exe"
sprites = ["motion_info.psb.m"]
