name = "Steins;Gate Linear Bounded Phenogram Steam"
description = """# Extracts Steins;Gate Linear Bounded Phenogram Steam version files.\n
Character conversion is supported to plain .PNG files for chara.mpk.
"""
filetype = "mpk"
path = "SG_Phenogram/USRDIR/"
sprites = ["chara.mpk"]
processor = "lay"
pfiletype = "lay"
